Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest: 80, host: 8090
    config.vm.network "public_network", ip: "192.168.1.139"
  end